using System.Collections.Generic;

namespace UniPlaySong.Services
{
    // Which settings each left-rail group owns. This is the ONLY place that partition is written
    // down: SettingsResetService reads it, and SettingsResetCoverageTests proves it covers every
    // setting exactly once. Add a setting without filing it here and the test fails by name.
    //
    // Note what is NOT here: default values. A group reset copies from a pristine
    // UniPlaySongSettings, so the defaults live once, on the backing fields. The hand-written
    // handlers this replaces restated them, and had drifted.
    internal static class SettingsGroups
    {
        internal const string About = "About";
        internal const string Setup = "Setup";
        internal const string QuickStart = "Quick Start";
        internal const string General = "General";
        internal const string Playback = "Playback";
        internal const string Pauses = "Pauses";
        internal const string LiveEffects = "Live Effects";
        internal const string Gamification = "Gamification";
        internal const string Library = "Library";
        internal const string Advanced = "Advanced";

        internal static readonly IReadOnlyDictionary<string, string[]> Map =
            new Dictionary<string, string[]>
            {
                [About] = new string[]
                {
                    // no resettable settings yet
                },
                [Setup] = new string[]
                {
                    nameof(UniPlaySongSettings.AutoCheckHintsOnStartup),
                    // Follows its toggle from Advanced -> Cleanup to Setup -> Automations. The
                    // map decides which group's Reset owns a setting, so it has to move with
                    // the UI or the wrong button resets it.
                    nameof(UniPlaySongSettings.AutoDeleteMusicOnGameRemoval),
                    nameof(UniPlaySongSettings.AutoDownloadOnGameInstall),
                    nameof(UniPlaySongSettings.AutoDownloadOnLibraryUpdate),
                    nameof(UniPlaySongSettings.AutoNormalizeAfterDownload),
                    nameof(UniPlaySongSettings.CookieMode),
                    nameof(UniPlaySongSettings.CustomCookiesFilePath),
                    nameof(UniPlaySongSettings.CustomHintsDatabasePath),
                    nameof(UniPlaySongSettings.EnableSearchCache),
                    nameof(UniPlaySongSettings.EnableYouTubeChannelWhitelist),
                    nameof(UniPlaySongSettings.MaxConcurrentDownloads),
                    nameof(UniPlaySongSettings.SearchCacheDurationDays),
                    nameof(UniPlaySongSettings.UseCustomHintsDatabase),
                    nameof(UniPlaySongSettings.UseFirefoxCookies),
                    nameof(UniPlaySongSettings.WhitelistedYouTubeChannelIds),
                },
                [QuickStart] = new string[]
                {
                    // no resettable settings yet
                },
                [General] = new string[]
                {
                    nameof(UniPlaySongSettings.AutoTagOnLibraryUpdate),
                    nameof(UniPlaySongSettings.EnableSongListCache),
                    nameof(UniPlaySongSettings.HideNowPlayingForDefaultMusic),
                    nameof(UniPlaySongSettings.ShowDefaultMusicIndicator),
                    nameof(UniPlaySongSettings.ShowDesktopMediaControls),
                    nameof(UniPlaySongSettings.ShowNowPlayingInTopPanel),
                    nameof(UniPlaySongSettings.ShowTaskbarMediaControls),
                },
                [Playback] = new string[]
                {
                    nameof(UniPlaySongSettings.AutoPlayOnFirstLaunchDesktop),
                    nameof(UniPlaySongSettings.BackupCustomMusicPath),
                    nameof(UniPlaySongSettings.CustomRotationGameIds),
                    nameof(UniPlaySongSettings.DefaultMusicContinueSameSong),
                    nameof(UniPlaySongSettings.DefaultMusicFolderPath),
                    nameof(UniPlaySongSettings.DefaultMusicPath),
                    nameof(UniPlaySongSettings.DefaultMusicSourceOption),
                    nameof(UniPlaySongSettings.DefaultMusicStatusPoolIds),
                    nameof(UniPlaySongSettings.EnableDefaultMusic),
                    nameof(UniPlaySongSettings.EnableMusic),
                    nameof(UniPlaySongSettings.EnablePreviewMode),
                    nameof(UniPlaySongSettings.EnableRandomPickerMusic),
                    nameof(UniPlaySongSettings.FilterModeEnabled),
                    nameof(UniPlaySongSettings.ForceDefaultMusicOverride),
                    nameof(UniPlaySongSettings.GamePropFilterEnabled),
                    nameof(UniPlaySongSettings.GamePropFilterGenreIds),
                    nameof(UniPlaySongSettings.GamePropFilterPlatformIds),
                    nameof(UniPlaySongSettings.GamePropFilterSourceIds),
                    nameof(UniPlaySongSettings.MusicOnlyForInstalledGames),
                    nameof(UniPlaySongSettings.MusicState),
                    nameof(UniPlaySongSettings.NostalgiaMode),
                    nameof(UniPlaySongSettings.NostalgiaStatusIds),
                    nameof(UniPlaySongSettings.PlayOnlyOnGameSelect),
                    nameof(UniPlaySongSettings.PreviewDuration),
                    nameof(UniPlaySongSettings.RadioCustomFolderPath),
                    nameof(UniPlaySongSettings.RadioModeEnabled),
                    nameof(UniPlaySongSettings.RadioMusicSource),
                    nameof(UniPlaySongSettings.RandomizeBundledTrackOnStartup),
                    nameof(UniPlaySongSettings.RandomizeDefaultMusicOnEnd),
                    nameof(UniPlaySongSettings.RandomizeOnEverySelect),
                    nameof(UniPlaySongSettings.RandomizeOnMusicEnd),
                    nameof(UniPlaySongSettings.SelectedBundledPreset),
                    nameof(UniPlaySongSettings.HoverSettleEnabled),
                    nameof(UniPlaySongSettings.HoverSettleSeconds),
                    nameof(UniPlaySongSettings.ResumeDefaultMusicPosition),
                    nameof(UniPlaySongSettings.ResumeGameMusicPosition),
                    nameof(UniPlaySongSettings.SkipFirstSelectionAfterModeSwitch),
                    nameof(UniPlaySongSettings.SpotifySkipOnGap),
                    nameof(UniPlaySongSettings.StopAfterSongEnds),
                    nameof(UniPlaySongSettings.SuppressPlayniteBackgroundMusic),
                    nameof(UniPlaySongSettings.UseNativeMusicAsDefault),
                },
                [Pauses] = new string[]
                {
                    nameof(UniPlaySongSettings.ExternalAudioDebounceSeconds),
                    nameof(UniPlaySongSettings.ExternalAudioExcludedApps),
                    nameof(UniPlaySongSettings.ExternalAudioInstantPause),
                    nameof(UniPlaySongSettings.FocusLossIgnoreBrief),
                    nameof(UniPlaySongSettings.FocusLossStayPaused),
                    nameof(UniPlaySongSettings.IdleTimeoutMinutes),
                    nameof(UniPlaySongSettings.KeepPausedAfterExternalAudio),
                    nameof(UniPlaySongSettings.PauseOnExternalAudio),
                    nameof(UniPlaySongSettings.PauseOnFocusLoss),
                    nameof(UniPlaySongSettings.PauseOnGameStart),
                    nameof(UniPlaySongSettings.PauseOnIdle),
                    nameof(UniPlaySongSettings.PauseOnMinimize),
                    nameof(UniPlaySongSettings.PauseOnSystemLock),
                    nameof(UniPlaySongSettings.PauseWhenInSystemTray),
                    nameof(UniPlaySongSettings.RadioPlaysThroughGames),
                },
                [LiveEffects] = new string[]
                {
                    nameof(UniPlaySongSettings.AdvancedReverbTuningEnabled),
                    nameof(UniPlaySongSettings.ApplyLiveEffectsToSpotify),
                    nameof(UniPlaySongSettings.BitcrusherBitDepth),
                    nameof(UniPlaySongSettings.BitcrusherDownsample),
                    nameof(UniPlaySongSettings.BitcrusherEnabled),
                    nameof(UniPlaySongSettings.CalmDownFadeLengthMultiplier),
                    nameof(UniPlaySongSettings.CalmDownLowPassCutoffHz),
                    nameof(UniPlaySongSettings.CalmDownModeEnabled),
                    nameof(UniPlaySongSettings.CalmDownTransitionDurationSeconds),
                    nameof(UniPlaySongSettings.CalmDownVolumeMultiplier),
                    nameof(UniPlaySongSettings.ChorusDepth),
                    nameof(UniPlaySongSettings.ChorusEnabled),
                    nameof(UniPlaySongSettings.ChorusMix),
                    nameof(UniPlaySongSettings.ChorusRate),
                    nameof(UniPlaySongSettings.CrossfadeDurationSeconds),
                    nameof(UniPlaySongSettings.DynamicColorBottom),
                    nameof(UniPlaySongSettings.DynamicColorTop),
                    nameof(UniPlaySongSettings.DynMinBrightnessBottom),
                    nameof(UniPlaySongSettings.DynMinBrightnessTop),
                    nameof(UniPlaySongSettings.DynMinSatBottom),
                    nameof(UniPlaySongSettings.DynMinSatTop),
                    nameof(UniPlaySongSettings.EffectChainPreset),
                    nameof(UniPlaySongSettings.EnableIconGlow),
                    nameof(UniPlaySongSettings.EnableIconGlowPulse),
                    nameof(UniPlaySongSettings.EnableIconGlowSpin),
                    nameof(UniPlaySongSettings.EnableIconGlowSpinAcceleration),
                    nameof(UniPlaySongSettings.EnableListIconGlow),
                    nameof(UniPlaySongSettings.EnableSidebarGlow),
                    nameof(UniPlaySongSettings.EnableTrueCrossfade),
                    nameof(UniPlaySongSettings.FadeInDuration),
                    nameof(UniPlaySongSettings.FadeOutBeforeSongEnd),
                    nameof(UniPlaySongSettings.FadeOutBeforeSongEndDuration),
                    nameof(UniPlaySongSettings.FadeOutDuration),
                    nameof(UniPlaySongSettings.FullscreenVolumeBoostPercent),
                    nameof(UniPlaySongSettings.HighPassCutoff),
                    nameof(UniPlaySongSettings.HighPassEnabled),
                    nameof(UniPlaySongSettings.IconGlowAudioSensitivity),
                    nameof(UniPlaySongSettings.IconGlowIntensity),
                    nameof(UniPlaySongSettings.IconGlowPreset),
                    nameof(UniPlaySongSettings.IconGlowPulseSpeed),
                    nameof(UniPlaySongSettings.IconGlowSize),
                    nameof(UniPlaySongSettings.IconGlowSpinSpeed),
                    nameof(UniPlaySongSettings.IdleVolumeTimeoutMinutes),
                    nameof(UniPlaySongSettings.LiveEffectsEnabled),
                    nameof(UniPlaySongSettings.LowerVolumeOnIdle),
                    nameof(UniPlaySongSettings.LowPassCutoff),
                    nameof(UniPlaySongSettings.LowPassEnabled),
                    nameof(UniPlaySongSettings.MakeupGain),
                    nameof(UniPlaySongSettings.MakeupGainEnabled),
                    nameof(UniPlaySongSettings.MusicVolume),
                    nameof(UniPlaySongSettings.ReverbAllpassFeedback),
                    nameof(UniPlaySongSettings.ReverbDamping),
                    nameof(UniPlaySongSettings.ReverbDryGain),
                    nameof(UniPlaySongSettings.ReverbEnabled),
                    nameof(UniPlaySongSettings.ReverbHfDampingMax),
                    nameof(UniPlaySongSettings.ReverbHfDampingMin),
                    nameof(UniPlaySongSettings.ReverbMix),
                    nameof(UniPlaySongSettings.ReverbPreDelay),
                    nameof(UniPlaySongSettings.ReverbReverberance),
                    nameof(UniPlaySongSettings.ReverbRoomSize),
                    nameof(UniPlaySongSettings.ReverbStereoWidth),
                    nameof(UniPlaySongSettings.ReverbToneHigh),
                    nameof(UniPlaySongSettings.ReverbToneLow),
                    nameof(UniPlaySongSettings.ReverbWetGain),
                    nameof(UniPlaySongSettings.ReverbWetGainMultiplier),
                    nameof(UniPlaySongSettings.SelectedReverbPreset),
                    nameof(UniPlaySongSettings.SelectedStylePreset),
                    nameof(UniPlaySongSettings.SelectedVizPreset),
                    nameof(UniPlaySongSettings.ShowSpectrumVisualizer),
                    nameof(UniPlaySongSettings.SidebarGlowMode),
                    nameof(UniPlaySongSettings.SlowAmount),
                    nameof(UniPlaySongSettings.SlowEnabled),
                    nameof(UniPlaySongSettings.StereoWidenerEnabled),
                    nameof(UniPlaySongSettings.StereoWidenerWidth),
                    nameof(UniPlaySongSettings.SubtleListGlow),
                    nameof(UniPlaySongSettings.TremoloDepth),
                    nameof(UniPlaySongSettings.TremoloEnabled),
                    nameof(UniPlaySongSettings.TremoloRate),
                    nameof(UniPlaySongSettings.VizBarGainBoost),
                    nameof(UniPlaySongSettings.VizBassGain),
                    nameof(UniPlaySongSettings.VizBassGravityBias),
                    nameof(UniPlaySongSettings.VizBleedAmount),
                    nameof(UniPlaySongSettings.VizColorTheme),
                    nameof(UniPlaySongSettings.VizCompression),
                    nameof(UniPlaySongSettings.VizFftFallHigh),
                    nameof(UniPlaySongSettings.VizFftFallLow),
                    nameof(UniPlaySongSettings.VizFftRiseHigh),
                    nameof(UniPlaySongSettings.VizFftRiseLow),
                    nameof(UniPlaySongSettings.VizFftSize),
                    nameof(UniPlaySongSettings.VizFftTimerMode),
                    nameof(UniPlaySongSettings.VizGradientEnabled),
                    nameof(UniPlaySongSettings.VizGravity),
                    nameof(UniPlaySongSettings.VizOpacityMin),
                    nameof(UniPlaySongSettings.VizPeakHoldMs),
                    nameof(UniPlaySongSettings.VizSmoothFall),
                    nameof(UniPlaySongSettings.VizSmoothRise),
                    nameof(UniPlaySongSettings.VizTrebleGain),
                },
                [Gamification] = new string[]
                {
                    nameof(UniPlaySongSettings.AbandonedSoundPath),
                    nameof(UniPlaySongSettings.AbandonedSoundType),
                    nameof(UniPlaySongSettings.AbandonedToastDurationSeconds),
                    nameof(UniPlaySongSettings.AbandonedToastMessage),
                    nameof(UniPlaySongSettings.AbandonedToastTheme),
                    nameof(UniPlaySongSettings.AchievementSoundPack),
                    nameof(UniPlaySongSettings.AchievementSoundPath),
                    nameof(UniPlaySongSettings.AchievementSoundType),
                    nameof(UniPlaySongSettings.ApplyLiveEffectsToJingles),
                    nameof(UniPlaySongSettings.CapstoneAchievementSoundPath),
                    nameof(UniPlaySongSettings.CelebrateBeaten),
                    nameof(UniPlaySongSettings.CelebrationSoundPath),
                    nameof(UniPlaySongSettings.CelebrationSoundType),
                    nameof(UniPlaySongSettings.CelebrationToastDurationSeconds),
                    nameof(UniPlaySongSettings.CelebrationToastTheme),
                    nameof(UniPlaySongSettings.CommonAchievementSoundPath),
                    nameof(UniPlaySongSettings.ControlUpDetectSoundPath),
                    nameof(UniPlaySongSettings.ControlUpDetectSoundType),
                    nameof(UniPlaySongSettings.EnableAbandonedSound),
                    nameof(UniPlaySongSettings.EnableAchievementSound),
                    nameof(UniPlaySongSettings.EnableCompletionCelebration),
                    nameof(UniPlaySongSettings.EnableControlUpDetectSound),
                    nameof(UniPlaySongSettings.HiddenAchievementSoundPath),
                    nameof(UniPlaySongSettings.RareAchievementSoundPath),
                    nameof(UniPlaySongSettings.SelectedAbandonedJingle),
                    nameof(UniPlaySongSettings.SelectedAchievementJingle),
                    nameof(UniPlaySongSettings.SelectedCelebrationJingle),
                    nameof(UniPlaySongSettings.SelectedControlUpDetectJingle),
                    nameof(UniPlaySongSettings.ShowAbandonedToast),
                    nameof(UniPlaySongSettings.ShowCelebrationToast),
                    nameof(UniPlaySongSettings.UltraRareAchievementSoundPath),
                    nameof(UniPlaySongSettings.UncommonAchievementSoundPath),
                },
                [Library] = new string[]
                {
                    nameof(UniPlaySongSettings.ConversionBitrate),
                    nameof(UniPlaySongSettings.ConversionKeepOriginals),
                    nameof(UniPlaySongSettings.ConversionTargetFormat),
                    nameof(UniPlaySongSettings.DoNotPreserveOriginals),
                    nameof(UniPlaySongSettings.NormalizationCodec),
                    nameof(UniPlaySongSettings.NormalizationLoudnessRange),
                    nameof(UniPlaySongSettings.NormalizationSuffix),
                    nameof(UniPlaySongSettings.NormalizationTargetLoudness),
                    nameof(UniPlaySongSettings.NormalizationTruePeak),
                    nameof(UniPlaySongSettings.PreciseTrimSuffix),
                    nameof(UniPlaySongSettings.SkipAlreadyNormalized),
                    nameof(UniPlaySongSettings.TrimSuffix),
                },
                [Advanced] = new string[]
                {
                    nameof(UniPlaySongSettings.AudioBufferSamples),
                    nameof(UniPlaySongSettings.AutoLaunchSpotifyOnStartup),
                    nameof(UniPlaySongSettings.EnableDebugLogging),
                    nameof(UniPlaySongSettings.EnableMediaKeyControl),
                    nameof(UniPlaySongSettings.EnableToastAcrylicBlur),
                    nameof(UniPlaySongSettings.IdleAudioDeviceTeardownMinutes),
                    nameof(UniPlaySongSettings.NaudioFadeInCurve),
                    nameof(UniPlaySongSettings.NaudioFadeOutCurve),
                    nameof(UniPlaySongSettings.PauseOnThemeOverlay),
                    nameof(UniPlaySongSettings.PauseOnThemeVideo),
                    nameof(UniPlaySongSettings.PauseOnTrailer),
                    nameof(UniPlaySongSettings.PlaySoundOnDownloadComplete),
                    nameof(UniPlaySongSettings.ProgressBarPosition),
                    nameof(UniPlaySongSettings.PS5ThemeCompatMode),
                    nameof(UniPlaySongSettings.GameHoverDelayPatch),
                    nameof(UniPlaySongSettings.ShowMusicDashboard),
                    nameof(UniPlaySongSettings.ShowPeakMeter),
                    nameof(UniPlaySongSettings.ShowProgressBar),
                    nameof(UniPlaySongSettings.SpotifyExePath),
                    nameof(UniPlaySongSettings.ThemeCompatibleSilentSkip),
                    nameof(UniPlaySongSettings.ToastBlurMode),
                    nameof(UniPlaySongSettings.ToastBlurOpacity),
                    nameof(UniPlaySongSettings.ToastBlurTintColor),
                    nameof(UniPlaySongSettings.ToastBorderColor),
                    nameof(UniPlaySongSettings.ToastBorderThickness),
                    nameof(UniPlaySongSettings.ToastCornerRadius),
                    nameof(UniPlaySongSettings.ToastDurationMs),
                    nameof(UniPlaySongSettings.ToastEdgeMargin),
                    nameof(UniPlaySongSettings.ToastMaxHeight),
                    nameof(UniPlaySongSettings.ToastMinHeight),
                    nameof(UniPlaySongSettings.ToastWidth),
                },
            };

        // Machine-specific paths and live runtime state. No reset restores these.
        internal static readonly HashSet<string> NeverReset = new HashSet<string>
        {
            nameof(UniPlaySongSettings.ActiveMediaCanNext),
            nameof(UniPlaySongSettings.ActiveMediaCanPrevious),
            nameof(UniPlaySongSettings.ActiveMediaDurationText),
            nameof(UniPlaySongSettings.ActiveMediaHasMedia),
            nameof(UniPlaySongSettings.ActiveMediaIsMuted),
            nameof(UniPlaySongSettings.ActiveMediaIsPlaying),
            nameof(UniPlaySongSettings.ActiveMediaPositionText),
            nameof(UniPlaySongSettings.ActiveMediaProgress),
            nameof(UniPlaySongSettings.ActiveMediaSourceKind),
            nameof(UniPlaySongSettings.ActiveMediaSourceName),
            nameof(UniPlaySongSettings.ActiveMediaVolume),
            nameof(UniPlaySongSettings.ActiveQuickStartProfile),
            nameof(UniPlaySongSettings.BundledPresetMigrated),
            nameof(UniPlaySongSettings.FFmpegPath),
            nameof(UniPlaySongSettings.IsMusicChanged),
            nameof(UniPlaySongSettings.LastAutoLibUpdateAssetsDownload),
            nameof(UniPlaySongSettings.LastRandomizedBundledPreset),
            nameof(UniPlaySongSettings.LastUpsRadioSource),
            nameof(UniPlaySongSettings.NowPlayingAlbum),
            nameof(UniPlaySongSettings.NowPlayingAlbumArtPath),
            nameof(UniPlaySongSettings.NowPlayingArtist),
            nameof(UniPlaySongSettings.NowPlayingDuration),
            nameof(UniPlaySongSettings.NowPlayingGenre),
            nameof(UniPlaySongSettings.NowPlayingTitle),
            nameof(UniPlaySongSettings.QuickStartOriginalSettings),
            nameof(UniPlaySongSettings.SpotifyActive),
            nameof(UniPlaySongSettings.SwitchRadioMode),
            nameof(UniPlaySongSettings.ThemeOverlayActive),
            nameof(UniPlaySongSettings.VideoIsPlaying),
            nameof(UniPlaySongSettings.YtDlpPath),
        };
    }
}
