name: Bug Report
description: Create an issue to report a bug
title: "[BUG] "
labels: ["bug"]
body:
  - type: dropdown
    id: view-mode
    attributes:
      label: View Mode
      description: Is this bug occurring on Playnite Desktop, Fullscreen, or both?
      options:
        - Desktop
        - Fullscreen
        - Both
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: plugin-conflicts
    attributes:
      label: Specify conflicts with other plugins (if any)
      description: Describe specific issues when using other plugins (do not assume the developer knows what the other plugin is used for).
      placeholder: e.g., "When ScreenshotVisualizer is active, music stutters during video playback"
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional notes
      description: Add any other context here.
    validations:
      required: false
